"use client";
import { Bell, LayoutDashboard, LogOut, Search, Settings, UserRound, X } from "lucide-react";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

type Item={id:string;title:string;message:string|null;occurredAt:string|null;createdAt:string;readAt:string|null};
const initials=(name:string)=>name.trim().split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]?.toUpperCase()).join("")||"B";
const dateLabel=(v:string)=>{const d=new Date(v);return Number.isNaN(d.getTime())?"":new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}).format(d)};

export default function AccountHeaderActions(){
 const router=useRouter(); const [ready,setReady]=useState(false); const [auth,setAuth]=useState(false); const [name,setName]=useState(""); const [email,setEmail]=useState(""); const [items,setItems]=useState<Item[]>([]); const [unread,setUnread]=useState(0); const [notifs,setNotifs]=useState(false); const [profile,setProfile]=useState(false); const nr=useRef<HTMLDivElement>(null); const pr=useRef<HTMLDivElement>(null);
 useEffect(()=>{let active=true; const s=createClient(); (async()=>{const {data}=await s.auth.getSession(); const u=data.session?.user; if(!active)return; if(!u){setReady(true);return} setAuth(true); const [{data:p},{data:n}]=await Promise.all([s.from("profiles").select("display_name").eq("user_id",u.id).maybeSingle(),s.from("notifications").select("id,title,message,occurred_at,created_at,read_at").eq("user_id",u.id).order("created_at",{ascending:false}).limit(12)]); if(!active)return; const e=u.email??""; const meta=typeof u.user_metadata?.name==="string"?u.user_metadata.name:""; setEmail(e); setName(p?.display_name||meta||e.split("@")[0]||"Usuário"); const mapped=(n??[]).map(x=>({id:x.id,title:x.title,message:x.message,occurredAt:x.occurred_at,createdAt:x.created_at,readAt:x.read_at})); setItems(mapped); setUnread(mapped.filter(x=>!x.readAt).length); setReady(true)})(); return()=>{active=false}},[]);
 useEffect(()=>{const close=(e:MouseEvent)=>{const t=e.target as Node;if(nr.current&&!nr.current.contains(t))setNotifs(false);if(pr.current&&!pr.current.contains(t))setProfile(false)};document.addEventListener("mousedown",close);return()=>document.removeEventListener("mousedown",close)},[]);
 async function logout(){await createClient().auth.signOut();router.replace("/login");router.refresh()}
 async function toggleNotifs(){const next=!notifs;setNotifs(next);setProfile(false);if(!next||!unread)return;const ids=items.filter(x=>!x.readAt).map(x=>x.id);if(!ids.length)return;const readAt=new Date().toISOString();const {error}=await createClient().from("notifications").update({read_at:readAt}).in("id",ids);if(!error){setItems(c=>c.map(x=>ids.includes(x.id)?{...x,readAt}:x));setUnread(0)}}
 if(!ready||!auth)return null;
 return <div className="dashboard-header-actions account-header-actions">
  <button className="dashboard-search-trigger" type="button" aria-label="Buscar" onClick={()=>router.push("/#map")}><Search size={17}/><span>Buscar</span><kbd>⌘ K</kbd></button>
  <div className="dashboard-menu-anchor" ref={nr}><button className={`dashboard-icon-button ${notifs?"is-open":""}`} type="button" aria-label="Notificações" aria-expanded={notifs} onClick={toggleNotifs}><Bell size={18}/>{unread>0&&<span className="notification-badge">{unread>9?"9+":unread}</span>}</button>{notifs&&<div className="notification-popover" role="dialog" aria-label="Notificações"><div className="popover-heading"><div><span>CENTRAL</span><strong>Notificações</strong></div><button type="button" onClick={()=>setNotifs(false)} aria-label="Fechar notificações"><X size={16}/></button></div>{items.length===0?<div className="notification-empty"><div className="notification-empty-icon"><Bell size={21}/></div><strong>Nenhuma notificação</strong><p>Quando houver uma nova atividade no seu acompanhamento, ela aparecerá aqui.</p></div>:<div className="notification-list">{items.map(x=><article className={`notification-item ${!x.readAt?"is-unread":""}`} key={x.id}><i/><div><strong>{x.title}</strong>{x.message&&<p>{x.message}</p>}<time>{dateLabel(x.occurredAt||x.createdAt)}</time></div></article>)}</div>}</div>}</div>
  <Link className="dashboard-icon-button account-dashboard-button" href="/dashboard" aria-label="Ir para o dashboard" title="Dashboard"><LayoutDashboard size={18}/></Link>
  <div className="dashboard-menu-anchor" ref={pr}><button className={`dashboard-profile-button ${profile?"is-open":""}`} type="button" aria-label="Abrir perfil" aria-expanded={profile} onClick={()=>{setProfile(c=>!c);setNotifs(false)}}><span className="dashboard-profile-avatar" aria-hidden="true"><UserRound size={21} strokeWidth={1.8}/></span><span className="dashboard-profile-copy"><strong>{name}</strong><small>Minha conta</small></span></button>{profile&&<div className="profile-popover" role="dialog" aria-label="Perfil"><div className="profile-popover-user"><span className="profile-popover-avatar">{initials(name)}</span><div><strong>{name}</strong><span>{email}</span></div></div><Link className="profile-popover-settings" href="/settings" onClick={()=>setProfile(false)}><Settings size={16}/><span>Configurações</span></Link><div className="profile-popover-separator"/><button type="button" onClick={logout}><LogOut size={16}/>Sair da conta</button></div>}</div>
 </div>
}
