"use client";
import { ArrowDownRight, ArrowRight, ArrowUpRight, Bell, Info, Minus, ShieldCheck, UserRound } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import DashboardHeader, { DashboardNotification } from "./DashboardHeader";

type ExpenseTrend={current:number;previous:number;percentChange:number|null;monthlyValues:number[]};
type Followed={id:string;representative_external_id:string;representative_source:string;representative_name:string;representative_office:string|null;representative_state:string|null;created_at:string;photoUrl:string|null;expenseTrend:ExpenseTrend|null};
type Props={displayName:string;email:string;unreadNotifications:number;notifications:DashboardNotification[];followedMandates:Followed[]};

function moneyCompact(value:number){return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL",notation:"compact",maximumFractionDigits:1}).format(value)}
function Trend({trend,onOpen}:{trend:ExpenseTrend|null;onOpen:()=>void}){
 if(!trend)return <button type="button" className="followed-expense-trend is-unavailable" onClick={(event)=>{event.stopPropagation();onOpen()}} aria-label="Abrir despesas CEAP deste mandato"><small>DESPESAS CEAP</small><strong>—</strong><span>Dados insuficientes</span></button>;
 const pct=trend.percentChange;
 const direction=pct===null?"neutral":pct>0.05?"up":pct<-.05?"down":"neutral";
 const max=Math.max(...trend.monthlyValues,1);
 const label=pct===null?"Sem base anterior":`${pct>0?"+":""}${pct.toLocaleString("pt-BR",{maximumFractionDigits:1})}%`;
 return <button type="button" className={`followed-expense-trend is-${direction}`} onClick={(event)=>{event.stopPropagation();onOpen()}} aria-label="Abrir despesas CEAP deste mandato"><div className="expense-trend-label"><small>DESPESAS CEAP</small><span className="expense-trend-info" role="button" tabIndex={0} aria-label="Como a tendência de despesas é calculada" onClick={(event)=>{event.preventDefault();event.stopPropagation()}} onKeyDown={(event)=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();event.stopPropagation()}}}><Info size={9}/><span className="expense-trend-tooltip" role="tooltip">Variação das despesas CEAP registradas nos últimos 3 meses completos em comparação com os 3 meses completos anteriores. A variação não representa avaliação de desempenho.</span></span></div><div className="expense-trend-main">{direction==="up"?<ArrowUpRight size={14}/>:direction==="down"?<ArrowDownRight size={14}/>:<Minus size={14}/>}<strong>{label}</strong><span>{moneyCompact(trend.current)}</span></div><div className="expense-sparkline" aria-hidden="true">{trend.monthlyValues.map((value,index)=><i key={index} style={{height:`${Math.max(3,(value/max)*18)}px`}}/>)}</div><span>últimos 3 meses · vs. 3 anteriores</span></button>;
}

export default function DashboardShell({displayName,email,unreadNotifications,notifications,followedMandates}:Props){
 const firstName=displayName.split(" ")[0]||"você";
 const router=useRouter();
 return <main className="dashboard-page"><DashboardHeader displayName={displayName} email={email} notifications={notifications} unreadNotifications={unreadNotifications}/><section className="dashboard-content"><div className="dashboard-welcome"><div><span className="dashboard-kicker">PAINEL PESSOAL</span><h1>Olá, {firstName}.</h1><p>Acompanhe mandatos e concentre em um só lugar as atualizações públicas que você decidiu seguir.</p></div><div className="dashboard-status"><ShieldCheck size={14}/><span>Dados de fontes oficiais</span></div></div>
 <div className="dashboard-layout"><section className="dashboard-main-column"><article className="dashboard-panel dashboard-panel-primary"><div className="panel-heading panel-heading-spread"><div className="panel-heading-group"><div className="panel-icon"><UserRound size={18}/></div><div><small>ACOMPANHAMENTO</small><h2>Mandatos que você acompanha</h2></div></div><Link className="panel-heading-link" href="/#map">Explorar <ArrowRight size={14}/></Link></div>
 {followedMandates.length?<div className="followed-list">{followedMandates.map(item=><div className="followed-row" key={item.id} role="link" tabIndex={0} onClick={()=>router.push(`/mandate/${item.representative_external_id}`)} onKeyDown={(event)=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();router.push(`/mandate/${item.representative_external_id}`)}}}><div className="followed-row-content">{item.photoUrl?<img className="followed-row-photo" src={item.photoUrl} alt="" aria-hidden="true" loading="lazy"/>:<span className="followed-row-photo followed-row-photo-placeholder" aria-hidden="true"><UserRound size={14}/></span>}<div className="followed-row-copy"><small>{item.representative_office||"Mandato"}</small><strong>{item.representative_name}</strong><span>{item.representative_state||"BR"}</span></div></div><Trend trend={item.expenseTrend} onOpen={()=>router.push(`/mandate/${item.representative_external_id}?tab=expenses`)}/><ArrowRight className="followed-row-arrow" size={15}/></div>)}</div>:<div className="dashboard-empty-state"><div className="empty-orbit"><UserRound size={24}/></div><strong>Nenhum mandato acompanhado</strong><p>Escolha mandatos para transformar este painel em uma visão pessoal da atividade pública.</p><Link className="dashboard-primary-link" href="/#map">Explorar o mapa <ArrowRight size={15}/></Link></div>}</article></section>
 <aside className="dashboard-side-column"><article className="dashboard-panel dashboard-activity-panel"><div className="panel-heading panel-heading-spread"><div className="panel-heading-group"><div className="panel-icon"><Bell size={18}/></div><div><small>LINHA DO TEMPO</small><h2>Atividade recente</h2></div></div><span className="panel-muted-label">Atualizações verificáveis</span></div>{notifications.length?<div className="dashboard-feed">{notifications.slice(0,8).map(n=><div className="dashboard-feed-item" key={n.id}><i/><div><strong>{n.title}</strong>{n.message&&<p>{n.message}</p>}<span>{new Date(n.occurredAt||n.createdAt).toLocaleDateString("pt-BR")}</span></div></div>)}</div>:<div className="dashboard-activity-empty"><span className="activity-empty-dot"/><div><strong>Nenhuma atividade para exibir</strong><p>As atualizações dos mandatos acompanhados serão organizadas aqui em ordem cronológica.</p></div></div>}</article></aside></div></section></main>;
}
